import 'package:flutter/foundation.dart';
import '../models/user_model.dart';
import '../models/attendance_session_model.dart';
import '../models/attendance_record_model.dart';
import '../services/firebase_service.dart';
import '../services/location_service.dart';

/// Provider handling QR validation, distance computation, duplicate checks, and submission logs.
class AttendanceProvider with ChangeNotifier {
  final FirebaseService _firebaseService = FirebaseService();
  final LocationService _locationService = LocationService();

  List<AttendanceRecordModel> _history = [];
  bool _isLoadingHistory = false;
  bool _isSubmitting = false;
  String? _errorMessage;

  List<AttendanceRecordModel> get history => _history;
  bool get isLoadingHistory => _isLoadingHistory;
  bool get isSubmitting => _isSubmitting;
  String? get errorMessage => _errorMessage;

  /// Resets error state variables.
  void clearError() {
    _errorMessage = null;
    notifyListeners();
  }

  /// Loads attendance history logs for a specific student.
  Future<void> loadAttendanceHistory(String studentId) async {
    _isLoadingHistory = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _history = await _firebaseService.getStudentAttendanceHistory(studentId);
    } catch (e) {
      _errorMessage = "Failed to load history: ${e.toString()}";
    } finally {
      _isLoadingHistory = false;
      notifyListeners();
    }
  }

  /// Core feature: Validates a scanned qrToken, performs GPS checks, checks duplicates, and logs attendance.
  Future<bool> scanAndSubmitAttendance({
    required String qrToken,
    required UserModel student,
  }) async {
    _isSubmitting = true;
    _errorMessage = null;
    notifyListeners();

    try {
      // 1. Get current student coordinates (asks location permission dynamically if needed)
      final position = await _locationService.getCurrentLocation();
      final double studentLatitude = position.latitude;
      final double studentLongitude = position.longitude;

      // 2. Fetch session from Firestore by qrToken (returns active sessions only)
      final session = await _firebaseService.getActiveSessionByToken(qrToken);

      // 3. Validate Session properties (active == true, expiresAt > current time)
      if (session == null) {
        throw "Invalid QR";
      }

      // Check double-safeguard in case Firestore triggers date difference latency
      if (session.expiresAt.isBefore(DateTime.now())) {
        throw "Invalid QR";
      }

      // 4. Prevent duplicates: Search attendance collection where sessionId == current and studentId == current
      final bool isDuplicate = await _firebaseService.checkDuplicateAttendance(
        session.sessionId,
        student.studentId,
      );

      if (isDuplicate) {
        throw "Attendance already submitted.";
      }

      // 5. Calculate Distance using Geolocator
      final double distance = _locationService.calculateDistance(
        startLatitude: session.latitude,
        startLongitude: session.longitude,
        endLatitude: studentLatitude,
        endLongitude: studentLongitude,
      );

      // 6. Submit Attendance (Create document)
      final record = AttendanceRecordModel(
        attendanceId: '', // Autogenerated by Firestore add()
        sessionId: session.sessionId,
        studentId: student.studentId,
        studentName: student.name,
        timestamp: DateTime.now(),
        distance: distance,
        courseName: session.courseName,
      );

      await _firebaseService.submitAttendance(record);

      // 7. Reload attendance history
      await loadAttendanceHistory(student.studentId);

      _isSubmitting = false;
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = e.toString();
      _isSubmitting = false;
      notifyListeners();
      return false;
    }
  }

  /// Developer Helper: Creates a mock active session in Firestore for testing.
  Future<String> createDebugSession({
    required String qrToken,
    required double latitude,
    required double longitude,
    required String courseName,
  }) async {
    return await _firebaseService.createMockSession(
      qrToken: qrToken,
      latitude: latitude,
      longitude: longitude,
      duration: const Duration(minutes: 30),
      courseName: courseName,
    );
  }
}
