import 'package:cloud_firestore/cloud_firestore.dart';

/// Represents an attendance session generated by an admin.
/// Typically stored in Firestore at /attendance_sessions/{sessionId}
class AttendanceSessionModel {
  final String sessionId;
  final String adminId;
  final String qrToken;
  final DateTime createdAt;
  final DateTime expiresAt;
  final double latitude;
  final double longitude;
  final bool active;
  final String? courseName; // Optional field for showing friendly course title

  AttendanceSessionModel({
    required this.sessionId,
    required this.adminId,
    required this.qrToken,
    required this.createdAt,
    required this.expiresAt,
    required this.latitude,
    required this.longitude,
    required this.active,
    this.courseName,
  });

  /// Factory constructor to create an [AttendanceSessionModel] from a Firestore [DocumentSnapshot].
  factory AttendanceSessionModel.fromFirestore(DocumentSnapshot doc) {
    final Map<String, dynamic> data = doc.data() as Map<String, dynamic>? ?? {};

    // Safely parse timestamps
    final dynamic rawCreatedAt = data['createdAt'];
    final dynamic rawExpiresAt = data['expiresAt'];

    DateTime parsedCreatedAt = DateTime.now();
    if (rawCreatedAt is Timestamp) {
      parsedCreatedAt = rawCreatedAt.toDate();
    } else if (rawCreatedAt is String) {
      parsedCreatedAt = DateTime.tryParse(rawCreatedAt) ?? DateTime.now();
    }

    DateTime parsedExpiresAt = DateTime.now().add(const Duration(minutes: 10));
    if (rawExpiresAt is Timestamp) {
      parsedExpiresAt = rawExpiresAt.toDate();
    } else if (rawExpiresAt is String) {
      parsedExpiresAt = DateTime.tryParse(rawExpiresAt) ?? parsedExpiresAt;
    }

    // Safely parse coordinates (could be int or double)
    double parsedLatitude = 0.0;
    if (data['latitude'] != null) {
      parsedLatitude = (data['latitude'] is num)
          ? (data['latitude'] as num).toDouble()
          : double.tryParse(data['latitude'].toString()) ?? 0.0;
    }

    double parsedLongitude = 0.0;
    if (data['longitude'] != null) {
      parsedLongitude = (data['longitude'] is num)
          ? (data['longitude'] as num).toDouble()
          : double.tryParse(data['longitude'].toString()) ?? 0.0;
    }

    return AttendanceSessionModel(
      sessionId: doc.id,
      adminId: data['adminId'] as String? ?? '',
      qrToken: data['qrToken'] as String? ?? '',
      createdAt: parsedCreatedAt,
      expiresAt: parsedExpiresAt,
      latitude: parsedLatitude,
      longitude: parsedLongitude,
      active: data['active'] as bool? ?? false,
      courseName: data['courseName'] as String?,
    );
  }

  /// Converts the [AttendanceSessionModel] instance to a Map structure for Firestore.
  Map<String, dynamic> toMap() {
    return {
      'adminId': adminId,
      'qrToken': qrToken,
      'createdAt': Timestamp.fromDate(createdAt),
      'expiresAt': Timestamp.fromDate(expiresAt),
      'latitude': latitude,
      'longitude': longitude,
      'active': active,
      if (courseName != null) 'courseName': courseName,
    };
  }
}
